title: Saswat's Hideout
author: Saswat "Aiden" Das
email: thenicec1pher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A smorgasbord of my thoughts and interests. Proceed with Caution.
  Computers, math, literature, music and everything fine.
# social links
twitter_username: SaswatDas19 # DO NOT include the @ character, or else the build will fail!
github_username:  SaswatD27 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
